#!/usr/bin/env python3
"""Materialize Smalltalk Android preview source. No credentials or signing keys.
Run from the repository root, then use Gradle 8.7 in android/.
"""
from pathlib import Path
import shutil
FILES = {
    'android/settings.gradle': "pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }\nrootProject.name = 'Smalltalk'\ninclude ':app'\n",
    'android/build.gradle': "plugins { id 'com.android.application' version '8.3.2' apply false }\n",
    'android/app/build.gradle': "plugins { id 'com.android.application' }\nandroid {\n namespace 'com.vertex.smalltalk'\n compileSdk 34\n defaultConfig { applicationId 'com.vertex.smalltalk.preview'; minSdk 24; targetSdk 34; versionCode 1; versionName '0.1-preview' }\n flavorDimensions 'client'\n productFlavors {\n  user { dimension 'client'; buildConfigField 'boolean', 'ADMIN_CLIENT', 'false'; resValue 'string', 'app_name', 'Smalltalk Preview' }\n  admin { dimension 'client'; applicationIdSuffix '.admin'; buildConfigField 'boolean', 'ADMIN_CLIENT', 'true'; resValue 'string', 'app_name', 'Smalltalk Admin Preview' }\n }\n buildFeatures { buildConfig true }\n buildTypes { debug { debuggable true }; release { minifyEnabled false } }\n}\n",
    'android/app/src/main/AndroidManifest.xml': '<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:allowBackup="false" android:label="@string/app_name" android:theme="@android:style/Theme.Material.NoActionBar" android:usesCleartextTraffic="false"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity></application></manifest>\n',
    'android/app/src/main/java/com/vertex/smalltalk/MainActivity.java': 'package com.vertex.smalltalk;\nimport android.app.Activity;\nimport android.os.Bundle;\nimport android.webkit.WebView;\nimport android.webkit.WebViewClient;\nimport android.webkit.WebResourceRequest;\nimport android.webkit.WebResourceResponse;\nimport java.io.InputStream;\npublic class MainActivity extends Activity {\n private WebView view;\n @Override public void onCreate(Bundle state){super.onCreate(state);view=new WebView(this);setContentView(view);view.getSettings().setJavaScriptEnabled(!BuildConfig.ADMIN_CLIENT);view.getSettings().setDomStorageEnabled(false);view.getSettings().setAllowFileAccess(false);view.getSettings().setAllowContentAccess(false);view.setWebViewClient(new WebViewClient(){\n @Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest request){android.net.Uri u=request.getUrl();if(!"https".equals(u.getScheme())||!"app.local".equals(u.getHost()))return new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));String path=u.getPath();if(path==null||path.contains(".."))return new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));String file=path.substring(1);try{InputStream stream=getAssets().open(file);String mime=file.endsWith(".html")?"text/html":file.endsWith(".css")?"text/css":"text/javascript";return new WebResourceResponse(mime,"UTF-8",stream);}catch(Exception e){return new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));}}\n @Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return true;}\n });view.loadUrl("https://app.local/"+(BuildConfig.ADMIN_CLIENT?"admin/":"")+"index.html");}\n @Override public void onDestroy(){if(view!=null){view.destroy();view=null;}super.onDestroy();}\n}\n',
    'admin/index.html': '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'self\'; script-src \'none\'; connect-src \'none\'; img-src \'none\'; object-src \'none\'; base-uri \'none\'; form-action \'none\'"><title>Smalltalk Admin preview</title><link rel="stylesheet" href="style.css"></head><body><main><small>VERTEX · ADMIN PREVIEW</small><h1>Smalltalk Admin</h1><aside>Access denied. Backend and privileged roles are not configured. No user data is visible in this preview.</aside><h2>Controls under development</h2><ul><li>User review and bans</li><li>Reports and content moderation</li><li>Configuration and audit history</li></ul><p>Live admin content access must be disclosed to users. Authentication and server-side role checks are required; a separate app alone is not a security boundary.</p></main></body></html>\n',
    'admin/style.css': '*{box-sizing:border-box}:root{font-family:system-ui;color:#ecf5f2;background:#11211f}body{margin:0}main{max-width:820px;margin:24px auto;padding:28px;background:#19302b;border-radius:20px}header{display:flex;justify-content:space-between;gap:16px;align-items:center}small{letter-spacing:2px;color:#83d8b5;font-weight:700}h1{font-size:38px;margin:6px 0}h2{font-size:23px}button{border:0;border-radius:10px;padding:12px 16px;font:inherit;font-weight:600;cursor:pointer;background:#c4f1dd;color:#15352b;min-height:46px}header button{background:#2b4940;color:#e8f4ef}aside{background:#294139;border:1px solid #4e6d5e;padding:16px;border-radius:12px;margin:24px 0;line-height:1.5}nav{display:flex;gap:8px;flex-wrap:wrap}nav button{flex:1;background:#29463d;color:#c4d8cf}nav .active{background:#c4f1dd;color:#15352b}section{min-height:300px;padding-top:16px}p,footer{line-height:1.5}.muted,footer{color:#b2c8bc}#messages{min-height:130px;max-height:350px;overflow:auto;background:#122a23;border-radius:12px;padding:12px}.message{margin:8px 0 8px auto;background:#315b48;border-radius:12px 12px 0 12px;padding:12px;max-width:85%;overflow-wrap:anywhere;white-space:pre-wrap}.message small{display:block;font-size:11px;letter-spacing:0;color:#c2d8ca;margin-top:6px}label{display:block;margin:18px 0 8px}.compose{display:flex;gap:8px}input{flex:1;min-width:0;font:inherit;padding:12px;border:1px solid #74917d;border-radius:10px;background:#122a23;color:#fff}footer{font-size:13px;border-top:1px solid #3d594b;padding-top:16px;margin-top:24px}#board{display:grid;grid-template-columns:repeat(3,75px);gap:8px}#board button{height:75px;font-size:26px;background:#315b48;color:#fff}button:focus-visible,input:focus-visible{outline:3px solid #ffca75;outline-offset:3px}@media(max-width:600px){main{margin:10px;padding:18px}h1{font-size:32px}header{align-items:flex-start}header button{font-size:13px;max-width:110px}.compose{flex-wrap:wrap}.compose button{width:100%}nav button{padding:12px 8px;font-size:14px}}\n',
}
for name, source in FILES.items():
    dest = Path(name)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(source)
assets = Path('android/app/src/main/assets')
assets.mkdir(parents=True, exist_ok=True)
for name in ('index.html', 'style.css', 'app.mjs', 'core.mjs'):
    shutil.copyfile(name, assets / name)
(assets / 'admin').mkdir(exist_ok=True)
for name in ('index.html', 'style.css'):
    shutil.copyfile(Path('admin') / name, assets / 'admin' / name)
print('Android source ready. Set ANDROID_HOME, then run gradle 8.7 in android/. Unsigned previews only.')
